# mysql
mysql:
    build: ./mysql
    ports:
        - "8306:3306"
    environment:
        - MYSQL_DATABASE=mysql
        - MYSQL_USER=developer
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=123456
    volumes:
        - /opt/data/mysql:/var/lib/mysql
    restart: always

# php7
php7:
    build: ./php7
    ports:
        - "9009:9000"
    links:
        - mysql
    volumes:
#        - ./php7/config/php.ini:/usr/local/php/lib/php.ini:ro
        - /var/www/html:/usr/local/nginx/html
    restart: always

# web
nginx:
    build: ./nginx
    ports:
        - "8000:80"
        - "8430:443"
    links:
        - php7
    volumes:
        - ./nginx/config/myapp.conf:/usr/local/nginx/conf/myapp.conf:ro
        - /var/www/html:/usr/local/nginx/html
    restart: always

# myapp
myqpp:
    build: ./myapp
    ports:
        - "8001:80"
        - "8431:443"
    links:
        - php7
    volumes:
        - ./myapp/config/myapp.conf:/usr/local/nginx/conf/myapp.conf:ro
        - /var/www/html:/usr/local/nginx/html
    restart: always